apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "drift-report-plugin.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "drift-report-plugin.name" . }}
    chart: {{ include "drift-report-plugin.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "drift-report-plugin.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        app: {{ include "drift-report-plugin.name" . }}
        release: {{ .Release.Name }}
        logging: "true"
    spec:
{{- if .Values.global.tolerations }}  
      tolerations:
{{ toYaml .Values.global.tolerations | indent 8 }}
{{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.full }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            # - name: GRPC_VERBOSITY
            #   value: "DEBUG"
            # - name: GRPC_TRACE
            #   value: "all,-timer_check"
            - name: HTTP_PORT
              value: "5000"
            - name: SELF_ADDR
              value: "http://{{ template "drift-report-plugin.fullname" . }}:{{ .Values.service.port }}"
            - name: MANAGER_ADDR
              value: "{{ template "manager.fullname" . }}:{{ .Values.global.manager.service.ports.grpc }}"
            - name: ENDPOINT_OVERRIDE
            {{- if .Values.global.persistence.url }}
              value: "{{ .Values.global.persistence.url }}"
            {{- else }}
              value: "http://{{ template "minio.fullname" . }}:{{ .Values.global.persistence.service.ports.api }}"
            {{- end }}
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: {{ template "minio.fullname" . }}
                  key: root-user
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ template "minio.fullname" . }}
                  key: root-password
            - name: POSTGRES_USER
              value: "{{ .Values.global.postgresql.postgresqlUsername }}"
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ template "postgresql.fullname" . }}
                  key: postgresql-password
            - name: POSTGRES_HOST
              value: {{ if .Values.global.postgresql.url }}"{{ .Values.global.postgresql.url }}"{{ else }}"{{ template "postgresql.fullname" . }}" {{ end }}
            - name: POSTGRES_PORT
              value: "{{ .Values.global.postgresql.servicePort }}"
            - name: DB_CONNECTION_STRING
              value: postgresql://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@$(POSTGRES_HOST):$(POSTGRES_PORT)/stat_plugin
          ports:
            - name: http
              containerPort: 5000
              protocol: TCP
          livenessProbe:
            initialDelaySeconds: 20
            httpGet:
              path: /api/health
              port: http
          readinessProbe:
            initialDelaySeconds: 20
            httpGet:
              path: /api/health
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
