apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: {{ include "drift-report-plugin.fullname" . }}
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: {{ include "drift-report-plugin.name" . }}
      release: {{ .Release.Name }}