{{- if and .Values.standaloneCollector.enabled .Values.global.metrics -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "opentelemetry-collector.fullname" . }}
  labels:
    {{- include "opentelemetry-collector.labels" . | nindent 4 }}
data:
  relay: |
    {{- include "opentelemetry-collector.standaloneCollectorConfig" . | nindent 4 -}}
{{- end }}
