{{- if and .Values.agentCollector.enabled .Values.global.metrics -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "opentelemetry-collector.fullname" . }}-agent
  labels:
    {{- include "opentelemetry-collector.labels" . | nindent 4 }}
data:
  relay: |
    {{- include "opentelemetry-collector.agentCollectorConfig" . | nindent 4 -}}
{{- end }}
