{{- if and .Values.serviceAccount.create .Values.global.metrics -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "opentelemetry-collector.serviceAccountName" . }}
  labels:
    {{- include "opentelemetry-collector.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
