apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "manager.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "manager.fullname" . }}
    chart: {{ template "manager.fullname" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "manager.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        logType: "scala"
        app: {{ template "manager.name" . }}
        release: {{ .Release.Name }}
        logging: "true"
    spec:
{{- if .Values.global.tolerations }}  
      tolerations:
{{ toYaml .Values.global.tolerations | indent 8 }}
{{- end }} 
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.full }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - "-Dconfig.file=/etc/manager/k8s.conf"
            - "-Dcom.sun.management.jmxremote.port=5555"
            - "-Dcom.sun.management.jmxremote.rmi.port=5555"
            - "-Djava.rmi.server.hostname=localhost"
            - "-Dcom.sun.management.jmxremote.authenticate=false"
            - "-Dcom.sun.management.jmxremote.ssl=false"
          ports:
            - name: http
              containerPort: {{ .Values.containerPorts.http }}
              protocol: TCP
            - name: grpc
              containerPort: {{ .Values.containerPorts.grpc }}
              protocol: TCP
          env: 
            - name: AWS_REGION
              value: "us-west-1"
            - name: HOST
              value: {{ template "manager.fullname" . }}
            - name: HTTP_PORT
              value: "{{ .Values.global.manager.service.ports.http }}"
            - name: GRPC_PORT
              value: "{{ .Values.global.manager.service.ports.grpc }}"
            - name: MINIO_HOST
              value: {{ template "minio.fullname" . }}
            - name: MINIO_PORT
              value: "{{ .Values.global.persistence.service.ports.api }}"
            - name: MINIO_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ template "minio.fullname" . }}
                  key: root-user
            - name: MINIO_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ template "minio.fullname" . }}
                  key: root-password
            - name: DATABASE_HOST
              value: {{ if .Values.global.postgresql.url }}"{{ .Values.global.postgresql.url }}"{{ else }}"{{ template "postgresql.fullname" . }}" {{ end }}
            - name: DATABASE_NAME
              value: "{{ .Values.global.postgresql.postgresqlDatabase }}"
            - name: DATABASE_USERNAME
              value: "{{ .Values.global.postgresql.postgresqlUsername }}"
            - name: DATABASE_PORT
              value: "{{ .Values.global.postgresql.servicePort }}"
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ template "postgresql.fullname" . }}
                  key: postgresql-password
          readinessProbe:
            exec:
              command:
              - "grpc_health_probe"
              - "-addr"
              - ":{{ .Values.global.manager.service.ports.grpc }}"
            initialDelaySeconds: 10
          livenessProbe:
            exec:
              command:
              - "grpc_health_probe"
              - "-addr"
              - ":{{ .Values.global.manager.service.ports.grpc }}"
            initialDelaySeconds: 20
          volumeMounts:
            - name: {{ template "manager.fullname" . }}-config
              mountPath: "/etc/manager/"
              readOnly: true
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: {{ template "manager.fullname" . }}-config
          configMap:
            name: {{ template "manager.fullname" . }}-config
            items:
              - key: k8s.conf
                path: k8s.conf
