{{- if .Values.exportMetrics.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "manager.fullname" . }}-otel-config
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "manager.fullname" . }}
    chart: {{ template "manager.fullname" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
{{ (.Files.Glob "config/otel-collector-config.yaml").AsConfig | indent 2 }}
{{- end }}
