apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: {{ include "manager.fullname" . }}
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: {{ include "manager.name" . }}
      release: {{ .Release.Name }}