apiVersion: v1
kind: Service
metadata:
  name: "{{ template "manager.fullname" . }}"
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "manager.fullname" . }}
    chart: {{ include "manager.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.global.manager.service.type }}
  ports:
    - port: {{ .Values.global.manager.service.ports.http }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.global.manager.service.ports.grpc }}
      targetPort: grpc
      protocol: TCP
      name: grpc
    - port: {{ .Values.containerPorts.jmx }}
      targetPort: jmx
      protocol: TCP
      name: jmx
  {{- if .Values.monitoring.enabled }}
    - port: 5556
      targetPort: jmx-exporter
      protocol: TCP
      name: jmx-exporter
  {{- end }}
  selector:
    app: {{ include "manager.name" . }}
    release: {{ .Release.Name }}
