apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "profiler.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "profiler.name" . }}
    chart: {{ include "profiler.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "profiler.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        app: {{ include "profiler.name" . }}
        release: {{ .Release.Name }}
        logging: "true"
    spec:
{{- if .Values.global.tolerations }}  
      tolerations:
{{ toYaml .Values.global.tolerations | indent 8 }}
{{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.full }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: MINIO_ENDPOINT
            {{- if .Values.global.persistence.url }}
              value: "{{ .Values.global.persistence.url }}"
            {{- else }}
              value: "http://{{ template "minio.fullname" . }}:{{ .Values.global.persistence.service.ports.api }}"
            {{- end }}
            - name: HTTP_HOST
              value: "{{ template "profiler.fullname" . }}"
            - name: HTTP_PORT
              value: "5001"
            - name: MANAGER_ADDR
              value: "{{ template "manager.fullname" . }}:{{ .Values.global.manager.service.ports.grpc }}"
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: {{ template "minio.fullname" . }}
                  key: root-user
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ template "minio.fullname" . }}
                  key: root-password
          ports:
            - name: http
              containerPort: 5001
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: http
          readinessProbe:
            httpGet:
              path: /health
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
