repos:
  - repo: https://github.com/norwoodj/helm-docs
    rev: v1.5.0
    hooks:
      - id: helm-docs
        args:
          - --sort-values-order=file
          # Make the tool search for charts only under the `example-charts` directory
          - --chart-search-root=helm
