{{- if .Values.global.metrics }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "otel-collector.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "otel-collector.fullname" . }}
    chart: {{ include "otel-collector.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.ports.pprof }}
      targetPort: pprof
      protocol: TCP
      name: pprof
    - port: {{ .Values.service.ports.metrics }}
      targetPort: metrics
      protocol: TCP
      name: metrics
    - port: {{ .Values.service.ports.exporterMetrics }}
      targetPort: export-metrics
      protocol: TCP
      name: export-metrics
    - port: {{ .Values.service.ports.healthCheck }}
      targetPort: health-check
      protocol: TCP
      name: health-check
    - port: {{ .Values.service.ports.grpc }}
      targetPort: grpc
      protocol: TCP
      name: grpc
    - port: {{ .Values.service.ports.zpages }}
      targetPort: zpages
      protocol: TCP
      name: zpages
  selector:
    app: {{ include "otel-collector.name" . }}
    release: {{ .Release.Name }}
{{- end }}
