version: "3.8"

services:
  otel-collector:
    image: otel/opentelemetry-collector-contrib-dev:latest
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./infra/otel/otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "1888:1888"   # pprof extension
      - "8888:8888"   # Prometheus metrics exposed by the collector
      - "8889:8889"   # Prometheus exporter metrics
      - "13133:13133" # health_check extension
      - "4317"        # OTLP gRPC receiver
      - "55670:55679" # zpages extension
    depends_on:
      - prometheus

  prometheus:
    command:
      --config.file=/etc/prometheus/config.yaml
      --enable-feature=remote-write-receiver
    image: prom/prometheus:v2.31.1
    volumes:
      - "./infra/prometheus/:/etc/prometheus:ro"
    ports:
      - "9092:9090"

  grafana:
    depends_on:
      - prometheus
    image: grafana/grafana:8.3.0
    volumes:
      - "./infra/grafana/datasources/:/etc/grafana/provisioning/datasources/"
    ports:
      - "9093:3000"
