global:
  ui: 
    ingress:
      enabled: true
      host: "hydromonitoring.local" # Domain name for the frontend ingress.
      path: "/" # Path, which will match the service.
      issuer: "letsencrypt-prod" # A name of the cert-manager issuer name, configured within the 
                                 # cluster.

  postgresql:
    url: ""
    postgresqlUsername: "root" # required to be set
    postgresqlPassword: "root" # required to be set
    postgresqlDatabase: "monitoring"
    servicePort: 5432

  persistence:
    url: "" # Endpoint for the object storage. Compatible with S3 or Minio.
    mode: "minio"
    ingress:
      enabled: false
      host: "hydrosphere-minio.local"
    accessKey: "ACCESSKEYEXAMPLE" # accesskeyid for s3 or minio
    secretKey: "SECRETKEYEXAMPLE" # secretkeyid for s3 or minio
    #region: "us-west-1" # region for s3
    service:
      ports:
        api: 9000
        console: 9001
  
  manager:
    service:
      http_port: 8080
      grpc_port: 8081
  tolerations: []

manager:
  image: 
    full: hydrosphere/monitoring-manager:latest

drift-report-plugin:
  image: 
    full: hydrosphere/drift-report-plugin:latest

shell-ui:
  image: 
    full: hydrosphere/shell-ui:latest
