apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "shell-ui.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "shell-ui.name" . }}
    chart: {{ include "shell-ui.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "shell-ui.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        logType: "nginx"
        app: {{ include "shell-ui.name" . }}
        release: {{ .Release.Name }}
        logging: "true"
    spec:
{{- if .Values.global.tolerations }}  
      tolerations:
{{ toYaml .Values.global.tolerations | indent 8 }}
{{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.full }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: MANAGER_HOST
              value: {{ template "manager.fullname" . }}
            - name: MANAGER_HTTP_PORT
              value: "{{ .Values.global.manager.service.ports.http }}"
            - name: INGRESS_PATH
              value: {{ if .Values.global.ui.ingress.enabled }}'//{{ .Values.global.ui.ingress.host }}{{ trimSuffix "/" .Values.global.ui.ingress.path }}/'{{else}}'/'{{end}}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
