{{- if .Values.global.ui.ingress.enabled }}
{{- if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1
{{- else -}}
apiVersion: extensions/v1
{{- end }}
kind: Ingress
metadata:
  name: "{{ include "shell-ui.fullname" . }}"
  namespace: {{ .Release.Namespace }}
  labels:
    app: "{{ include "shell-ui.name" . }}"
    chart: "{{ include "shell-ui.chart" . }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
  annotations:
    cert-manager.io/cluster-issuer: {{ .Values.global.ui.ingress.issuer | quote }}
    kubernetes.io/ingress.class: "nginx"
    kubernetes.io/tls-acme: "true"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/client-max-body-size: "0"
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
    nginx.ingress.kubernetes.io/proxy-buffering: "off"
    nginx.ingress.kubernetes.io/proxy-http-version: "1.1"
    nginx.ingress.kubernetes.io/proxy-request-buffering: "off"
    {{- if ne .Values.global.ui.ingress.path "/"}}
    nginx.ingress.kubernetes.io/rewrite-target: "/$2"
    {{- end }}
spec:
  rules:
    - host: {{ .Values.global.ui.ingress.host }}
      http:
        paths:
          - path: {{ .Values.global.ui.ingress.path }}
            pathType: Prefix
            backend:
              service:
                name: {{ template "shell-ui.fullname" . }}
                port:
                  number: {{ .Values.service.port }}
  tls:
  - hosts:
    - {{ .Values.global.ui.ingress.host }}
    secretName: "{{ .Release.Name }}-ui-tls"
{{- end }}