# Default values for drift-report-plugin.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

global:
  persistence:
    url: "" # Endpoint for the object storage. Compatible with S3 or Minio.
    service:
      ports:
        api: 9000

  manager:
    service:
      ports:
        http: 8080
        grpc: 8081
  tolerations: []

image:
  full: hydrosphere/drift-report-plugin:2807382e8f96b9e9d2fc2aab870c7f2288d1ce38
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 5000

podSecurityContext:
  runAsUser: 42069

securityContext:
  allowPrivilegeEscalation: false

podAnnotations: {}

resources: {}

nodeSelector: {}

affinity: {}
