
replicaCount: 1

global:
  ui: 
    ingress:
      enabled: false
      host: "hydromonitoring.local" # Domain name for the frontend ingress.
      path: "/" # Path, which will match the service.
      issuer: "letsencrypt-prod" # A name of the cert-manager issuer name, configured within the 
                                 # cluster.
  manager:
    service:
      http_port: 8080
  
  tolerations: []

image:
  full: hydrosphere/shell-ui:latest
  pullPolicy: Always

service:
  type: ClusterIP
  port: 80

podSecurityContext:
  runAsUser: 42069

securityContext:
  allowPrivilegeEscalation: false

podAnnotations: {}

ingress:
  enabled: true
  annotations: 
    kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  
  host: hydromonitoring.local
  path: '/'
  tls: []

resources: {}

nodeSelector: {}

affinity: {}
