# -- number of replicas
replicaCount: 1

global:
  ui: 
    ingress:
      # -- Enable frontend ingress
      enabled: false
      # -- Domain name for the frontend ingress
      host: "hydromonitoring.local"
      # -- Path, which will match the service
      path: "/" 
      # -- A name of the cert-manager issuer name, configured within the cluster
      issuer: "letsencrypt-prod"
  manager:
    service:
      ports:
        # -- Manager http port
        http: 8080

  # -- Tolerations for shell-ui pods
  tolerations: []

image:
  # -- shell-ui image
  full: hydrosphere/shell-ui:956ed6880e1f81a0890325292fccb49e92ac3024
  # -- shell-ui image pull policy
  pullPolicy: IfNotPresent

service:
  # -- Kubernetes Service type
  type: ClusterIP
  # -- shell-ui port
  port: 9090

podSecurityContext:
  # -- User ID for the container
  runAsUser: 42069

securityContext:
  # -- Container child process can gain more privileges than its parent
  allowPrivilegeEscalation: false

# -- Map of annotations to add to the pods
podAnnotations: {}

# -- Map of resources to add to the pods
resources: {}

# -- Node labels for shell-ui pods assignment
nodeSelector: {}

# -- Affinity for shell-ui pods assignment
affinity: {}
