# -- number of replicas
replicaCount: 1

global:
  ui: 
    ingress:
      # -- Enable frontend ingress
      enabled: false
      # -- Domain name for the frontend ingress
      host: "hydromonitoring.local"
      # -- Path, which will match the service
      path: "/" 
      # -- A name of the cert-manager issuer name, configured within the cluster
      issuer: "letsencrypt-prod"
  manager:
    service:
      ports:
        # -- Manager http port
        http: 8080

  # -- Tolerations for shell-ui pods
  ## ref: https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/
  tolerations: []

image:
  # -- shell-ui image
  full: hydrosphere/shell-ui:ca0b617da9d056da5a3d53344e286bb88a16faa2
  # -- shell-ui image pull policy
  pullPolicy: IfNotPresent

service:
  # -- Kubernetes Service type
  type: ClusterIP
  # -- shell-ui port
  port: 8080

podSecurityContext:
  # -- User ID for the container
  runAsUser: 42069

securityContext:
  # -- Container child process can gain more privileges than its parent
  allowPrivilegeEscalation: false

# -- Map of annotations to add to the pods
podAnnotations: {}

# -- Map of resources to add to the pods
## ref: https://kubernetes.io/docs/concepts/policy/resource-quotas/#compute-resource-quota
resources: {}

# -- Node labels for shell-ui pods assignment
## ref: https://kubernetes.io/docs/user-guide/node-selection/
nodeSelector: {}

# -- Affinity for shell-ui pods assignment
## ref: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#affinity-and-anti-affinity
affinity: {}
