manager:
  image: 
    full: hydrosphere/monitoring-manager:5724dd9c61f6a5bed5fbc8e5cb38c727cd331521

drift-report-plugin:
  image: 
    full: hydrosphere/drift-report-plugin:f83f8a181f8ef1827d457b019b8bbb985a6166ce

profiler:
  image: 
    full: hydrosphere/profiler:c47ab9b60b2377c04af5b04e48b6e316dd90ad2c

shell-ui:
  image: 
    full: hydrosphere/shell-ui:5a5b373655faa041df138f2ec824a380c256672d

global:
  ui:
    ingress:
      enabled: true
      host: "hydro-monitoring.dev.hydrosphere.io"
  
  persistence:
    url: ""
    mode: "minio"
    region: "us-west-2" # region for s3
  
  tolerations:
    - key: "node-type"
      operator: "Equal"
      value: "demo"
      effect: "NoSchedule"
