manager:
  image: 
    full: hydrosphere/monitoring-manager:94681b176d0e40adb8c3ab296b9eab78febcc214
  monitoring:
    enabled: true

drift-report-plugin:
  image: 
    full: hydrosphere/drift-report-plugin:90fec27ed9d27ccb499fc15a3d941d57d82b5370

profiler:
  image: 
    full: hydrosphere/profiler:d4e3e64ae874ed6ccc713fcf65b866cb20c24441

shell-ui:
  image: 
    full: hydrosphere/shell-ui:5f1fb20d1a665b0f91423db5b9c72c88df000896

global:
  ui:
    ingress:
      enabled: true
      host: "hydro-monitoring.dev.hydrosphere.io"
  
  persistence:
    url: ""
    mode: "minio"
    region: "us-west-2" # region for s3
  
  tolerations:
    - key: "node-type"
      operator: "Equal"
      value: "demo"
      effect: "NoSchedule"
