manager:
  image: 
    full: hydrosphere/monitoring-manager:0.1.0
  monitoring:
    enabled: true

drift-report-plugin:
  image: 
    full: hydrosphere/drift-report-plugin:0.1.0

profiler:
  image: 
    full: hydrosphere/profiler:0.1.0

shell-ui:
  image: 
    full: hydrosphere/shell-ui:0.1.0

opentelemetry-collector:
  config:
    exporters:
      prometheusremotewrite:
        endpoint: http://kube-prometheus-prometheus:9090/api/v1/write

global:
  ui:
    ingress:
      enabled: true
      host: "hydro-monitoring.dev.hydrosphere.io"
  
  persistence:
    url: ""
    mode: "minio"
    region: "us-west-2" # region for s3
  
  tolerations:
    - key: "node-type"
      operator: "Equal"
      value: "demo"
      effect: "NoSchedule"
