manager:
  image: 
    full: hydrosphere/monitoring-manager:5e41a730bea8ae15ea78b1e4c9583d0c47f5634c
  monitoring:
    enabled: true

drift-report-plugin:
  image: 
    full: hydrosphere/drift-report-plugin:4747ffeabcc572dd67ed727d5f59c75fc74cfd80

profiler:
  image: 
    full: hydrosphere/profiler:63e8001df93f5defac3994b84995558e040ccae2

shell-ui:
  image: 
    full: hydrosphere/shell-ui:8f842a38c0b1fcc75bf444b581fd709d012ab41c

opentelemetry-collector:
  config:
    exporters:
      prometheusremotewrite:
        endpoint: http://kube-prometheus-prometheus:9090/api/v1/write

global:
  ui:
    ingress:
      enabled: true
      host: "hydro-monitoring.dev.hydrosphere.io"
  
  persistence:
    url: ""
    mode: "minio"
    region: "us-west-2" # region for s3
  
  tolerations:
    - key: "node-type"
      operator: "Equal"
      value: "demo"
      effect: "NoSchedule"
