manager:
  image: 
    full: hydrosphere/monitoring-manager:0a6aa89e3056376a42609933ede9759538c11c29
  monitoring:
    enabled: true

drift-report-plugin:
  image: 
    full: hydrosphere/drift-report-plugin:98b502a4941e82aa2829b1e3e476bf42eca83846

profiler:
  image: 
    full: hydrosphere/profiler:63e8001df93f5defac3994b84995558e040ccae2

shell-ui:
  image: 
    full: hydrosphere/shell-ui:46427ff552b32b1f176815b3cfb4da570112c256

otel-collector:
  prometheusEndpoint: kube-prometheus-prometheus:9090

global:
  ui:
    ingress:
      enabled: true
      host: "hydro-monitoring.dev.hydrosphere.io"
  
  persistence:
    url: ""
    mode: "minio"
    region: "us-west-2" # region for s3
  
  tolerations:
    - key: "node-type"
      operator: "Equal"
      value: "demo"
      effect: "NoSchedule"
