manager:
  image: 
    full: hydrosphere/monitoring-manager:5724dd9c61f6a5bed5fbc8e5cb38c727cd331521

drift-report-plugin:
  image: 
    full: hydrosphere/drift-report-plugin:d14cb4ee0a709b3d85d1eee4f5518e4177b065b1

profiler:
  image: 
    full: hydrosphere/profiler:c47ab9b60b2377c04af5b04e48b6e316dd90ad2c

shell-ui:
  image: 
    full: hydrosphere/shell-ui:1586a31fb40194d335b3df5a169ee8f7273a683e

global:
  ui:
    ingress:
      enabled: true
      host: "hydro-monitoring.dev.hydrosphere.io"
  
  persistence:
    url: ""
    mode: "minio"
    region: "us-west-2" # region for s3
  
  tolerations:
    - key: "node-type"
      operator: "Equal"
      value: "demo"
      effect: "NoSchedule"
