manager:
  image: 
    full: hydrosphere/monitoring-manager:7240f4a2e98b0ecd5d390b6099faf80548f9b4e4

drift-report-plugin:
  image: 
    full: hydrosphere/drift-report-plugin:9bb9caf630d3247fba2a681f4fb4029b937fdef8

profiler:
  image: 
    full: hydrosphere/profiler:72c902059dc7db53247daf7a43f4ffbf05d659bc

shell-ui:
  image: 
    full: hydrosphere/shell-ui:1586a31fb40194d335b3df5a169ee8f7273a683e

global:
  ui:
    ingress:
      enabled: true
      host: "hydro-monitoring.dev.hydrosphere.io"
  
  persistence:
    url: ""
    mode: "minio"
    region: "us-west-2" # region for s3
  
  tolerations:
    - key: "node-type"
      operator: "Equal"
      value: "demo"
      effect: "NoSchedule"
