manager:
  image: 
    full: hydrosphere/monitoring-manager:0d14c97054eb6d76d9ab2876f51221231974f92e
  monitoring:
    enabled: true
  exportMetrics:
    # -- Exporting metrics option to opentelemetry-collector
    enabled: true
    # -- Prometheus endpoint within the cluster
    prometheusEndpoint: monitoring-kube-prometheus-prometheus:9090
  resources:
    limits:
      # -- The cpu limit for the container
      cpu: 1500m
      # -- The memory limit for the container
      memory: 2Gi
    requests:
      # -- The requested cpu for the container
      cpu: 500m
      # -- The requested memory for the container
      memory: 1Gi

drift-report-plugin:
  image: 
    full: hydrosphere/drift-report-plugin:9546de06c61d04a3f0f05744cf2421cd5f07f1a5

profiler:
  image: 
    full: hydrosphere/profiler:fd71e25f52e1baefd3aa1b40b40d41c18a76addc

shell-ui:
  image: 
    full: hydrosphere/shell-ui:ca0b617da9d056da5a3d53344e286bb88a16faa2

otel-collector:
  prometheusEndpoint: kube-prometheus-prometheus:9090

global:
  ui:
    ingress:
      enabled: true
      host: "hydro-monitoring.dev.hydrosphere.io"
  
  persistence:
    url: ""
    mode: "minio"
    region: "us-west-2" # region for s3
  
  tolerations:
    - key: "node-type"
      operator: "Equal"
      value: "demo"
      effect: "NoSchedule"
