manager:
  image: 
    full: hydrosphere/monitoring-manager:6bf7b627406890d0527a569f8f6c62c1a8402e71

drift-report-plugin:
  image: 
    full: hydrosphere/drift-report-plugin:3a78805d62f234e3738ccdfcb52618d7fcae8243

profiler:
  image: 
    full: hydrosphere/profiler:7558994af1c62562451864117e69201eb15a7751

shell-ui:
  image: 
    full: hydrosphere/shell-ui:20115fababf181e5394c862f8ecb37930094cba8

global:
  ui:
    ingress:
      enabled: true
      host: "hydro-monitoring.dev.hydrosphere.io"
  
  persistence:
    url: ""
    mode: "minio"
    region: "us-west-2" # region for s3
  
  tolerations:
    - key: "node-type"
      operator: "Equal"
      value: "demo"
      effect: "NoSchedule"
