manager:
  image: 
    full: hydrosphere/monitoring-manager:6bf7b627406890d0527a569f8f6c62c1a8402e71

drift-report-plugin:
  image: 
    full: hydrosphere/drift-report-plugin:184ffa62315c166cb40103b483e6ee6b40771321

profiler:
  image: 
    full: hydrosphere/profiler:2b37818b5dd323ab5bc4fae28b53485606703145

shell-ui:
  image: 
    full: hydrosphere/shell-ui:5a0ecce211796403cdf3a40ef63adec8af02523c

global:
  ui:
    ingress:
      enabled: true
      host: "hydro-monitoring.dev.hydrosphere.io"
  
  persistence:
    url: ""
    mode: "minio"
    region: "us-west-2" # region for s3
  
  tolerations:
    - key: "node-type"
      operator: "Equal"
      value: "demo"
      effect: "NoSchedule"
