manager:
  image: 
    full: hydrosphere/monitoring-manager:cbefb1790785961349f5cd3b96e27e44d0dec437
  monitoring:
    enabled: true

drift-report-plugin:
  image: 
    full: hydrosphere/drift-report-plugin:c7b6734287c780db25fdb1ffe3e73eeb7036b1da

profiler:
  image: 
    full: hydrosphere/profiler:f5409b4a791b93d46fb5024a9458dd06d20405d9

shell-ui:
  image: 
    full: hydrosphere/shell-ui:5f1fb20d1a665b0f91423db5b9c72c88df000896

global:
  ui:
    ingress:
      enabled: true
      host: "hydro-monitoring.dev.hydrosphere.io"
  
  persistence:
    url: ""
    mode: "minio"
    region: "us-west-2" # region for s3
  
  tolerations:
    - key: "node-type"
      operator: "Equal"
      value: "demo"
      effect: "NoSchedule"
