manager:
  image: 
    full: hydrosphere/monitoring-manager:b0afcdf93ca17dfd6757a4bcf02c80982f6d30ad
  monitoring:
    enabled: true
  exportMetrics:
    # -- Exporting metrics option to opentelemetry-collector
    enabled: true
    # -- Prometheus endpoint within the cluster
    prometheusEndpoint: monitoring-kube-prometheus-prometheus:9090
  resources:
    limits:
      # -- The cpu limit for the container
      cpu: 1500m
      # -- The memory limit for the container
      memory: 2Gi
    requests:
      # -- The requested cpu for the container
      cpu: 500m
      # -- The requested memory for the container
      memory: 1Gi

drift-report-plugin:
  image: 
    full: hydrosphere/drift-report-plugin:9546de06c61d04a3f0f05744cf2421cd5f07f1a5

profiler:
  image: 
    full: hydrosphere/profiler:bca177f8d71d9d8c93091f9a9fdf9a337582e194

shell-ui:
  image: 
    full: hydrosphere/shell-ui:c41e575569bb61995cfdcd64dcca647434800712

otel-collector:
  prometheusEndpoint: kube-prometheus-prometheus:9090

global:
  ui:
    ingress:
      enabled: true
      host: "hydro-monitoring.dev.hydrosphere.io"
  
  persistence:
    url: ""
    mode: "minio"
    region: "us-west-2" # region for s3
  
  tolerations:
    - key: "node-type"
      operator: "Equal"
      value: "demo"
      effect: "NoSchedule"
