# Default values for manager.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

global:
  postgresql:
    url: "" # Specify Postgresql connection string if you want to use an external Postgresql instance. 
            # If empty, an in-cluster deployment will be provisioned.
    postgresqlDatabase: "monitoring" # Postgresql database name. Used for an internal installation.
    postgresqlUsername: "postgres" # Postgresql username. Used for an internal installation.
    postgresqlPassword: "hydr0m0nit0ring" # Postgresql password. Used for an internal installation.
    servicePort: 5432

  tolerations: []

image:
  repository: hydrosphere/monitoring-manager
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: "latest"

service:
  type: ClusterIP
  http_port: 8080
  grpc_port: 8081

serviceAccount:
  create: true
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths: []
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources:
  limits:
   cpu: 1000m
   memory: 2Gi
  requests:
   cpu: 1000m
   memory: 1Gi

podAnnotations: {}

nodeSelector: {}

tolerations: []

affinity: {}
