# -- number of replicas
replicaCount: 1

global:
  postgresql:
    # -- Specify Postgresql connection string if you want to use an external Postgresql instance. If empty, an in-cluster deployment will be provisioned
    url: ""
    # -- Postgresql database name. Used for an internal installation
    postgresqlDatabase: "monitoring"
    # -- Postgresql username. Used for an internal installation
    postgresqlUsername: "postgres"
    # -- Postgresql password. Used for an internal installation
    postgresqlPassword: "hydr0m0nit0ring"
    # -- Postgresql service port
    servicePort: 5432
  
  manager:
    service:
      # -- Kubernetes Service type
      type: ClusterIP
      ports:
        # -- manager service http port
        http: 8080
        # -- manager service grpc port
        grpc: 8081
  
  persistence:
    # Endpoint for the object storage. Compatible with S3 or Minio
    url: ""
    service:
      ports:
        # -- Minio api port
        api: 9000

  # -- Tolerations for manager pods
  ## ref: https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/
  tolerations: []

image:
  # -- manager image
  full: hydrosphere/monitoring-manager:0a6aa89e3056376a42609933ede9759538c11c29
  # -- manager image pull policy
  pullPolicy: IfNotPresent

containerPorts:
  # -- manager container http port
  http: 8080
  # -- manager container grpc port
  grpc: 8081
  # -- manager container jmx port
  jmx: 5555

## ref: https://kubernetes.io/docs/concepts/policy/resource-quotas/#compute-resource-quota
resources:
  limits:
    # -- The cpu limit for the container
    cpu: 2000m
    # -- The memory limit for the container
    memory: 2Gi
  requests:
    # -- The requested cpu for the container
    cpu: 1000m
    # -- The requested memory for the container
    memory: 2Gi

monitoring:
  # -- JMX metrics monitoring
  enabled: false

exportMetrics:
  # -- export metrics
  enabled: false
  # -- Prometheus endpoint within the cluster
  prometheusEndpoint: monitoring-kube-prometheus-prometheus:9090
  ports:
    # -- pprof extension port
    pprof: 1888
    # -- Prometheus metrics exposed by the collector port
    metrics: 8888
    # -- Prometheus exporter metrics port
    exporterMetrics: 8889
    # -- health_check extension port
    healthCheck: 13133
    # -- OTLP gRPC receiver
    grpc: 4317
    # -- zpages extension port
    zpages: 55679

# -- Map of annotations to add to the pods
podAnnotations:
  # -- Scrape by prometheus
  prometheus.io/scrape: "true"
  # -- Port of jmx exporter
  prometheus.io/port: "5556"

# -- Node labels for manager pods assignment
## ref: https://kubernetes.io/docs/user-guide/node-selection/
nodeSelector: {}

# -- Affinity for manager pods assignment
## ref: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#affinity-and-anti-affinity
affinity: {}
