replicaCount: 1

global:
  postgresql:
    url: "" # Specify Postgresql connection string if you want to use an external Postgresql instance. 
            # If empty, an in-cluster deployment will be provisioned.
    postgresqlDatabase: "monitoring" # Postgresql database name. Used for an internal installation.
    postgresqlUsername: "postgres" # Postgresql username. Used for an internal installation.
    postgresqlPassword: "hydr0m0nit0ring" # Postgresql password. Used for an internal installation.
    servicePort: 5432
  
  manager:
    service:
      type: ClusterIP
      ports:
        http: 80
        grpc: 8081
  
  persistence:
    url: "" # Endpoint for the object storage. Compatible with S3 or Minio.
    service:
      ports:
        api: 9000

  tolerations: []

image:
  full: hydrosphere/monitoring-manager:7240f4a2e98b0ecd5d390b6099faf80548f9b4e4
  pullPolicy: IfNotPresent

containerPorts:
  http: 443
  grpc: 8081

resources:
  limits:
    cpu: 2000m
    memory: 2Gi
  requests:
    cpu: 1000m
    memory: 2Gi

podAnnotations: {}

nodeSelector: {}

affinity: {}
